# Generated by Django 6.0 on 2026-06-09 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_service_category_alter_service_created_at_and_more'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['name'], 'verbose_name': 'موظفة', 'verbose_name_plural': 'الموظفات'},
        ),
        migrations.AlterModelOptions(
            name='staffservice',
            options={'verbose_name': 'خدمة الموظفة', 'verbose_name_plural': 'خدمات الموظفات'},
        ),
        migrations.RemoveField(
            model_name='staff',
            name='email',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='hire_date',
        ),
        migrations.AddField(
            model_name='staff',
            name='name',
            field=models.CharField(default='موظفة', max_length=100, verbose_name='اسم الموظفة'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الجوال'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تحديث'),
        ),
        migrations.AlterField(
            model_name='staffservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='catalog.service', verbose_name='الخدمة'),
        ),
        migrations.AlterField(
            model_name='staffservice',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='scheduling.staff', verbose_name='الموظفة'),
        ),
    ]
