# Generated by Django 6.0 on 2026-06-11 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_staff_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('saturday', 'السبت'), ('sunday', 'الأحد'), ('monday', 'الإثنين'), ('tuesday', 'الثلاثاء'), ('wednesday', 'الأربعاء'), ('thursday', 'الخميس'), ('friday', 'الجمعة')], max_length=20, verbose_name='اليوم')),
                ('start_time', models.TimeField(verbose_name='وقت بداية العمل')),
                ('end_time', models.TimeField(verbose_name='وقت نهاية العمل')),
                ('is_active', models.BooleanField(default=True, verbose_name='متاحة للحجز')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='scheduling.staff', verbose_name='الموظفة')),
            ],
            options={
                'verbose_name': 'توفر الموظفة',
                'verbose_name_plural': 'توفر الموظفات',
                'ordering': ['staff', 'day_of_week', 'start_time'],
                'constraints': [models.UniqueConstraint(fields=('staff', 'day_of_week'), name='unique_staff_availability_per_day')],
            },
        ),
    ]
