# Generated by Django 5.2.4 on 2025-12-08 00:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'مستخدم', 'verbose_name_plural': 'المستخدمين'},
        ),
        migrations.AlterModelOptions(
            name='otp',
            options={'verbose_name': 'رمز التحقق', 'verbose_name_plural': 'أكواد التحقق'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='رقم الجوال يجب أن يتكون من 8 إلى 15 رقمًا', regex='^\\d{8,15}$')], verbose_name='رقم الجوال'),
        ),
    ]
