# Generated by Django 6.0 on 2026-06-11 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_options_alter_otp_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('customer', 'عميل'), ('staff', 'موظفة'), ('admin', 'مدير النظام')], default='customer', max_length=20, verbose_name='نوع الحساب'),
        ),
    ]
