# Generated by Django 5.2.4 on 2025-12-08 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at'], 'verbose_name': 'حجز', 'verbose_name_plural': 'الحجوزات'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='staff',
            field=models.CharField(blank=True, help_text='اسم الموظفة (اختياري)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('confirmed', 'مؤكد'), ('completed', 'مكتمل'), ('canceled', 'ملغي')], default='confirmed', max_length=20),
        ),
    ]
