# Generated by Django 5.2.4 on 2025-12-08 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_options_alter_booking_staff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
            ],
            options={
                'verbose_name': 'وقت متاح',
                'verbose_name_plural': 'الأوقات المتاحة',
                'ordering': ['time'],
            },
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='bookings',
                to='bookings.timeslot',
            ),
        ),
    ]
