# Generated by Django 6.0 on 2026-06-08 10:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_timeslot_alter_booking_time'),
        ('catalog', '0002_alter_service_category_alter_service_created_at_and_more'),
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_at_booking', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='السعر وقت الحجز')),
                ('duration_at_booking', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='المدة وقت الحجز بالدقائق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
            ],
            options={
                'verbose_name': 'خدمة داخل الحجز',
                'verbose_name_plural': 'الخدمات داخل الحجز',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات'),
        ),
        migrations.AddField(
            model_name='booking',
            name='staff_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='scheduling.staff', verbose_name='الموظفة'),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='إجمالي السعر'),
        ),
        migrations.AddField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تحديث'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(verbose_name='تاريخ الحجز'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.CharField(blank=True, help_text='حقل قديم من V1. الخدمات الجديدة تحفظ في BookingItem.', max_length=200, verbose_name='اسم الخدمة القديم'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='staff',
            field=models.CharField(blank=True, help_text='حقل قديم من V1.', max_length=100, null=True, verbose_name='اسم الموظفة القديم'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('confirmed', 'مؤكد'), ('completed', 'مكتمل'), ('canceled', 'ملغي'), ('no_show', 'لم يحضر')], default='confirmed', max_length=20, verbose_name='حالة الحجز'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='bookings.timeslot', verbose_name='الوقت'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='العميل'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='time',
            field=models.TimeField(verbose_name='الوقت'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['date', 'time'], name='bookings_bo_date_0bddd6_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='bookings_bo_status_233e96_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['staff_member', 'date'], name='bookings_bo_staff_m_2ba9f4_idx'),
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bookings.booking', verbose_name='الحجز'),
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_items', to='catalog.service', verbose_name='الخدمة'),
        ),
        migrations.AddConstraint(
            model_name='bookingitem',
            constraint=models.UniqueConstraint(fields=('booking', 'service'), name='unique_service_per_booking'),
        ),
    ]
