# Generated by Django 6.0 on 2026-06-08 23:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_bookingitem_booking_notes_booking_staff_member_and_more'),
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'confirmed'])), fields=('date', 'time', 'staff_member'), name='unique_active_booking_per_staff_time'),
        ),
    ]
