# Generated by Django 6.0 on 2026-06-10 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_unique_active_booking_per_staff_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('confirmed', 'مؤكد'), ('in_progress', 'قيد التنفيذ'), ('completed', 'مكتمل'), ('canceled', 'ملغي'), ('no_show', 'لم يحضر')], default='confirmed', max_length=20, verbose_name='حالة الحجز'),
        ),
    ]
